package simpletest;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.Map;

public class CalculatorTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void htmlFormExample() throws InterruptedException {
        driver.get("https://testpages.herokuapp.com/styled/index.html");
        driver.manage().window().maximize();

        Assert.assertEquals("Selenium Test Pages", driver.getTitle());

        Assert.assertEquals("Test Pages For Automating", driver.findElement(By.cssSelector("h1")).getText());

        Assert.assertEquals("This is a set of pages for automating or testing. Some of the examples are suitable for manual exploratory testing or JavaScript hacking."
                , driver.findElement(By.cssSelector(".explanation:nth-child(2) > p")).getText());


        driver.findElement(By.id("calculatetest")).click();

        Assert.assertEquals("Selenium Simplified Calculator", driver.getTitle());

        driver.findElement(By.id("number1")).sendKeys("5");
        driver.findElement(By.id("number2")).sendKeys("2");

        Thread.sleep(3000);

    }
}
