package withoutBDD.simpletest;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.util.Map;

public class HtmlFormExampleTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        driver.get("https://testpages.herokuapp.com/styled/index.html");
        driver.manage().window().maximize();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void htmlFormExample() throws InterruptedException {


        Assert.assertEquals("Selenium Test Pages", driver.getTitle());
        Assert.assertEquals("Test Pages For Automating", driver.findElement(By.cssSelector("h1")).getText());

        Assert.assertEquals("This is a set of pages for automating or testing. Some of the examples are suitable for manual exploratory testing or JavaScript hacking."
                , driver.findElement(By.cssSelector(".explanation:nth-child(2) > p")).getText());

        driver.findElement(By.id("htmlformtest")).click();

        Assert.assertEquals("HTML Form Elements", driver.getTitle());

        driver.findElement(By.name("username")).click();
        driver.findElement(By.name("username")).sendKeys("Ana");
        driver.findElement(By.name("password")).sendKeys("123456");
        driver.findElement(By.name("comments")).sendKeys("comentarioComments...");
        driver.findElement(By.cssSelector("tr:nth-child(5) input:nth-child(3)")).click();

        Assert.assertTrue(driver.findElement(By.cssSelector("tr:nth-child(5) input:nth-child(4)")).isSelected());
        Assert.assertTrue(driver.findElement(By.cssSelector("tr:nth-child(6) input:nth-child(3)")).isSelected());

        WebElement multipleSelect = driver.findElement(By.name("multipleselect[]"));

        Select selectOne = new Select(multipleSelect);
        selectOne.selectByVisibleText("Selection Item 2");

        WebElement dropdown = driver.findElement(By.name("dropdown"));

        Select selectTwo = new Select(dropdown);
        dropdown.click();

        selectTwo.selectByVisibleText("Drop Down Item 1");
        Thread.sleep(4000);

    }
}
